Example Command.xml
When there are three responses, and two have the default weighting of 1
and one of them has a weighting of 3, then it instead has a chance of
3/(1+1+3) = 3/5.
=> Examples: Fix chance in description of "weighting" attribute

Commands/Online.xml
Update the list of Tier 1 Joshimuz emotes which are used in the "Timed Emote Spam" command in the command collection "Online".
=> Online: update tier 1 emotes in "Timed Emote Spam" command

Commands/Online.xml
Update the list of Tier 1 Joshimuz emotes in the command collection "Online".
The josh55 emote has been deprecated and replaced with joshFanks.
=> Update josh55 to joshFanks in "Timed Emote Spam"

Commands/Generic.xml
ESA Winter 2021 has started, so saying "starts 12 February 2021" no
longer makes sense.
----
This pull request is a replacement for #6.
=> ESA: say that ESA Winter 2021 is live

Commands/VCS.xml
A command about going out of bound in GTA Vice City Stories to flip all vehicles has been added.
=> VCS: add out of bounds command

CommandCollections.xml, Commands/Generic.xml, Commands/MinecraftBingo.xml
- Fixed false `MC Bingo` command trigger in Generic
- Added colours to the `Colours meaning` command in MC Bingo
- Made the `MC Bingo` command collection independent by adding the lefthanded command and removing the `Minecraft` CC from the collection.
=> Make MC Bingo CC independent, fix command triggers

CommandCollections.xml, Commands/Minecraft.xml, Commands/MinecraftBingo.xml, Commands/MinecraftServer.xml
This change is so we can easily add commands for `Bingo`, `Server `and `Minecraft` itself. `Bingo` and `Server` will use the `Minecraft` command list.
Also, I was mistakenly referring to command lists as `CC` (command collection), therefore replace anything relating to `CC` with `CL.`
=> Split command lists into Minecraft, MCBingo and MCServer

Commands/iRacing.xml
Botimuz gets confused by "see" in "seem"/"seems", e.g. answering to
> Sventor: it seems every person writing in chat without a sub
> badge is being targeted monkaS
and
> yaoi69: seems like chat is helping to improve josh his bot
=> iRacing: VR chat: check forms of "see" more carefully

Commands/VCS.xml
Words in "it came out on Mobile" were in wrong order.
=> VCS: fix typo in "When LCS" command

Commands/Generic.xml
When sitrep is mentioned on screen, people keep asking for it.  Since
usually the title includes the link to the sitrep clip, let's just react
to the word "sitrep" as well.  Sitrep is only actual for iRacing
streams, but it won't hurt for other streams.
=> Generic: react to "sitrep" for !title command

CommandCollections.xml, Commands/GTA.xml, Commands/MTA.xml, Commands/SA.xml, Commands/SAAny.xml, Commands/SARando.xml, Commands/VCS.xml
Command  "Why no Radio" has been moved into new file `GTA.xml`. Its `<requiredwords>` block has been fixed and improved.
The word groups were updated so that first group is only "asking" words, second group is only verbs (plus "no"), and third group is only synonyms for "radio".
=> Fix "Why no Radio" command 

Commands/Generic.xml
A second command is needed because first command can't be updated to trigger on "bot schedule". And people already tried triggering Botimuz with "bot schedule" in the first 30 minutes of the stream.
=> More JDQ III command updates

Commands/Generic.xml
I'm not sure about `<timerRange>1800-3600</timerRange>` syntax because
there no live commands that use it, but it is described this way in
`Example Command.xml`.  The range of 1800 to 3600 seconds is copied from
"Timed Emote Spam" command in `Online.xml`.
=> JDQ III: add timed command for donation goals

Commands/Generic.xml
Twitch chat renders the anchor part of URL after "#" only when there is
a slash after the ".com".
=> Generic.xml: fix link in "GTA trilogy remaster/remake"

Commands/SA.xml, Commands/SANMG.xml, Commands/SANoAJS.xml
When one category is being run, people ask about other categories.  So
move the commands for category explanations from individual SA
categories files to the common SA.xml.
=> SA: move category explanations from individual category files

Commands/Generic.xml
The response was copy-pasted from commands that use /delete to delete
messages (<message deleted> and "Bot is dead").  But /ban and /timeout
need a chattername.  Compare to /ban in Braille ASCII graphic command
and /timeout in Commands/ChaosMod.xml.
Fixes #77.
=> Generic.xml: fix response of "Buy viewers ban"

Commands/Generic.xml, Commands/Online.xml
_"jurasjuras: how long is josh live?"_
-> Gives Alive time
_"jurasjuras: josh live for how long"_
-> Gives Uptime Metric
I have no idea, if the Commits are going to be safe/working fixes, but this overlap should probably be prevented by _unwantedwords_
=> Prevent live/alive overlap

CommandCollections.xml
ESA Winter 2022 event has ended, so switch from OfflineESA.xml to the
regular Offline.xml.
The response in Offline.xml refers to the schedule page on Twitch.  But
the schedule has been empty for quite a while now.  Not sure where to
poing the viewer instead.  Maybe Twitter?
=> CommandCollections.xml: use regular Offline.xml

Commands/Generic.xml
Timezones of _Europe/Dublin_ and _Europe/London_ should be identical.
=> Timezone to Ireland

Commands/Generic.xml
At the moment, esamarathon.com/schedule still has the Winter schedule,
so a separate URL for just ESA Summer 2022 has to be used.
=> Generic.xml: ESA Summer 2022

Commands/iRacing.xml
Just for today.
Missing:
- When Event (start)
- When Josh Drive / Stints 
- Name of driver Tony / Toni
Don't know if "Why hear twice" will occur.
Notes:
Event: iRacing CREVENTIC Endurance Race - iracing.com/iracing-creventic-endurance-series-returns-for-four-race-2022-season/
Length: 8 hours
Track: Hockenheimring - Grand Prix
Drivers: Joshua "Joshimuz" Edwards, Karl Townsend, Evgeniy "ca7nip" Pimenov, Sven "Sventor" Boxberg & Some Toni
Cars: 
- GT3 Cup: Porsche 911 GT3 Cup (992)
- **GT4:** Aston Martin Vantage GT4, BMW M4 GT4, **Porsche 718 Cayman GT4 Clubsport**
- Touring Car: Audi RS 3 LMS, Honda Civic Type R, Hyundai Elantra N TC, Hyundai Veloster
Karl does beginning
ca7nip does End
=> Endurance Race June 4th

Commands/Tightened.xml
If someone asks in chat why dont you blow up riders car, botimuz can respond saying it's for easter egg incentive
=> Added command for ESA tighted run arround easter eggs and ryders car

Commands/SA.xml
Added "stupid" to the List of unwanted words. This adresses a misfire of this command that happened on stream, since it contains the substring "up"
=> Edited 'Camera Flick' bot command

Commands/SADE.xml
Shortended link & made it more readable
- Mark AJS ""
- Reuse "jump" in explanation, as it is the whole strategy & in category title
- "after mission Ryder", not the character. For Noobs to understand
- Use milliseconds to properly mark this strat difficulty
- Corrected use of word "value"
- Removed VOD explanation
- Shortened link
=> Streamlined AJS response
