Commands/Generic.xml

Add a command for bidding farewell to the bot, to complement the
existing "Hi Bot" command.

Add "Bye Bot" command

---

Commands/Generic.xml

Are there any questions regarding games that could trigger the "how old" unwanted? If not, please add

Added how old

---

Commands/Generic.xml

Regarding someone entering "bot facecam delay"

Added 'facecam' to delay answer

---

Commands/Generic.xml

Good bot answer by WaterArko

---

Commands/Generic.xml

joshPaw answer to Hi Bot

---

Commands/Generic.xml

"What is WR" command has been updated to trigger on "Who has the WR?"

---

Commands/iRacing.xml

Question with 25 words got posted.

Removed maxWords from "Wheel and VR"

---

Commands/24hRace.xml

Revert part of commit d2aba51.

24hRace: fix duplicate word in "When Josh Drive?"

---

Commands/Generic.xml

> edisbeats: will ya play some SA?

Generic: add "play" to "When SA" command

---

Commands/VCS.xml

From today's stream:
> yazaeel: is there a reason why you run this game on controller?

VCS: Console & Console2: react to questions about input devices

---

CommandCollections.xml

Bug in `<unwantedtitlewords>` for GTA Any% streams has been fixed.

CommandCollections.xml: fix unwantedtitlewords for GTA Any%

---

Commands/Generic.xml

JDQ III was announced today on Twitter: https://twitter.com/Joshimuz/status/1423948188344586243

Generic.xml: update JDQ command for JDQ III

---

Commands/Generic.xml

Just a simple two word groups command for now.

start working on remake/remaster rumours command

---

Commands/Generic.xml

First commit "use faq.joshimuz.com as link" is definitely an improvement. Not so sure about the rest.

GTA Trilogy remake/remaster: fixes and tweaks

---

Commands/Generic.xml

Add more words to the "WHEN JDQ" command in Generic.xml to react to questions about schedule during JDQ III.

WHEN JDQ: add "schedule" and "link" to first group

---

Commands/Generic.xml

> jorss: is there a list of dono goals somewhere? :)

JDQ III: add "dono" to donation goals command

---

Commands/Generic.xml

Add "been out" and change past tense "happened" to infinitive "happen"
to accomodate messages like this one from today's stream:
> Dasha_Shengelia: nooooo i'm been out, what happening??

Generic.xml: tweak "I left why reset"

---

Commands/Online.xml

Timed Emote Spam: remove Botimuz follower emotes

---

Commands/Online.xml

Timed Emote Spam: add animated emotes

---

Commands/Generic.xml

This, obviously, won't check if it was from a subscriber with access to the emote, but still seems like a good addition.

Generic.xml: add "joshFanks bot"

---

Commands/Generic.xml

> 14:04 Introv7: what's happening with the subtitles?
> 14:04 Botimuz: Chaos + Rainbowizer Mod! Maximum Randomness enabled | Continuing JDQIII run
Botimuz reacted to "what"+"subtitles".

!title: make "title" wholeword="true"

---

Commands/iRacing.xml

Botimuz didn't react to a message from today's chat:
> 13:10:24 localparrot: is he using logitech pedals?

iRacing: add "pedals" to the setup command

---

Commands/24hRace.xml

Bot reacts to word "the" with this command.

24hRace.xml: wholeword="true" for "he"

---

Commands/24hRace.xml

Disabled Schedule, until schedule exists.
Some classes correction.

24h adjustments

---

Commands/24hRace.xml

Source: https://discord.com/channels/131720430326120449/131720430326120449/933803115617063003
Is that "schedule bullshit" text needed? https://github.com/Joshimuz/BotimuzCommands/commit/82b891e03296405b08d4a97fae65d606bb2ffa5e#diff-9b92db18c2e2e1d0ec2fb20a617e8a8451cce45631c19b5a7d3b8db7830e11e8

Schedule added

---

Commands/24hRace.xml

Directly link to Spreadsheet, on request, as it will be updated. 
My picture will run out-of-date

Changed 24h schedule link

---

Commands/Generic.xml

HVT2020: Wanna become famous? Buy followers, primes and viewers on cutt.ly/xxxxxxx

Buy viewers ban: New URL

---

Commands/Generic.xml

> 15:13:42 Jace: Bot wow
> 15:13:52 jerryjimjoe: bot is sentient

Good bot: add "wow" and "sentient"

---

Commands/Generic.xml

Not sure if this would be useful or not, but Shoshi had already gathered the links, so I've just put them into a Botimuz command.

Generic.xml: add "How did ESA go?" command

---

Commands/Generic.xml

Reason: "andrybak: what time is it in Dublin?"

Added Dublin to time command

---

Commands/iRacing.xml

- Name Toni Fiebiger
- Full racing car name (how iRacing calls it)
- Start/End of race
- Double voice (might happen, dunno)

Updated Endurance

---

Commands/iRacing.xml

Not important, just gives me the compulsion, until it's fixed.

British summer time

---

Commands/iRacing.xml

Event is over. Bot gives mis-responses

Removed Endurance race

---

Commands/MinecraftServer.xml

(weird whitespace diff, due to edit by Browser?)

MinecraftServer: Updated MC version

---

Commands/Generic.xml
Commands/Tightened.xml

Fix typos in Tightened, uncomment and update ESA When for ESA Winter 2024

Update Tightened and Generic

---

Commands/iRacing.xml

IMO I think the bot should answer how to bet when viewers are asking in plaintext.

Add command for iRacing Betting

---

SA Reset Reasons.txt

Josh died to a head scratch, lets immortalise the act

Update SA Reset Reasons Head Scratch

---

SA Reset Reasons.txt

Update SA Reset Reasons.txt

---

Commands/Generic.xml

Added Tech Issue command

---

SA Reset Reasons.txt

https://www.twitch.tv/joshimuz/clip/OnerousPrettyLapwingBIRB-4Oc-4yxyFhhYOrqu

Update SA reset reason: frozen van spawned upside-down

---

Commands/MTA.xml

Add MTA-Server Address

---

Commands/MTA.xml

Fixed duplicate command

---

SA Reset Reasons.txt

https://www.twitch.tv/joshimuz/clip/CharmingGleamingSparrowTriHard-k6wcnp6f6ZdNhlAK

SA reset reason: played a replay

---

Commands/Generic.xml

Updated GTAM command

---

SA Reset Reasons.txt

https://www.twitch.tv/joshimuz/clip/PowerfulYummyJaguarJKanStyle-JR21N2OWue9KgHoQ

SA reset reason: checked if car is sexy

---

Commands/SAMisc.xml

Done on mobile so sorry for any weird indents or formatting

Add yaoi69 to jumps word blacklist filter

---

CommandCollections.xml

Might be reason for Issue #143 , might be nothing but a beauty fix.

CommandCollections.xml: Corrected speedruncategory (SA DE Any%)
